### ISSUE TITLE
Possible to post articles as preprints with DOI number prior to acceptance?

### ISSUE THREAD

**Issue by pschloss** [openjournals/jose#10]
I am wondering whether there's been any discussions about JOSE (and JOSS) possibly issuing a DOI number to submitted manuscripts that are in review. That way the manuscripts would be citable as a preprint. I can imagine the logistics might be a challenge, but could see a manuscript keeping its DOI as it moves through peer review perhaps with a preprint/accepted badge on the PDF or manuscript metadata. This may be overly naive. 

I raise this idea because it appears next to impossible to get a JOSE manuscript posted to biorxiv without a meaningful amount of data. I appreciate the constraints the journal is under currently, but being able to have something citable would be helpful given the longer review times. I know we could do something through Zenodo, but that seems less than ideal since it wouldn't have a journal or preprint server behind it and as I understand it that DOI would be for the repo and not necessarily the manuscript.

**Comment by kyleniemeyer** [comment]
We have not discussed this, because while the final DOI is essentially "reserved" ahead of time, we only register the DOI upon publication. I'm also not sure about

> I know we could do something through Zenodo, but that seems less than ideal since it wouldn't have a journal or preprint server behind it and as I understand it that DOI would be for the repo and not necessarily the manuscript.

This isn't quite right—you can upload many kinds of artifacts to Zenodo, including articles/PDFs, and not just software repositories. So that seems the easiest solution for sure.

My personal opinion is that JOSS/JOSE/Open Journals should not get into this business, since there already are numerous preprint servers and other places to archive preprints. Many authors have already done this, at arXiv, Zenodo, etc.
