### ISSUE TITLE
Pre-submission enquiry

### ISSUE THREAD

**Issue by ludwigbothmann** [openjournals/jose#12]
Dear members of JOSE's editorial board,

recently we wrote an article where we propose core principles of developing open-source educational resources, discuss their benefits and ways to use these in blended learning scenarios and MOOCs. The pre-print can be found on arxiv: https://arxiv.org/abs/2107.14330

The paper is based on our experience in developing the open-source courses
- Automated Machine Learning (https://github.com/automl-edu/AutoMLLecture | https://ki-campus.org/courses/automl-luh2021) and
- Introduction to Machine Learning (https://github.com/compstat-lmu/lecture_i2ml | https://introduction-to-machine-learning.netlify.app/)
and on teaching those in blended learning scenarios at different universities where the authors are affiliated.

However, in the paper, we don't elaborate that much on the courses themselves and more on the underlying principles of developing such material collaboratively since we think that this should be an interesting contribution to the community.

Is such a paper eligible for publication in JOSE? We could also elaborate more on the concrete courses if this would fit more to the scope of JOSE.

Thank you very much for your thoughts!

Best regards
Ludwig

**Comment by labarba** [comment]
hello @ludwigbothmann – sincere apologies, but it turns out I wasn't "watching" this repository and have not come poking here in a long time (I had it set to "only when `@`-mentioned"... I changed it now).

You may have already gone to another venue, but in any case, I had a look at your preprint and it would not be in scope for JOSE. We may revisit this in the future with the editorial board, but the scope covers educational software, and learning modules using computation in some form. (Nice article, though! Very much aligned with my view and long-time practice.)
